[user]
name = "Kyle J Strand"
email = "kstrand@rigetti.com"

[ui]
# diff.tool = ["difft", "--color=always", "$left", "$right"]
diff-editor = "vscode"
merge-editor = "vscode"
paginate = "auto"
default-command = "status"
revsets-use-glob-by-default = true

[remotes.origin]
auto-track-created-bookmarks = "*"

[revsets]
log = "trunk()..@ | trunk()"

[experimental-advance-branches]
enabled-branches = ["glob:*"]
disabled-branches = ["main", "master", "glob:rigetti-integration-*", "glob:integration-rigetti-*", "local-only"]

[git]
# abandon-unreachable-commits = false
colocate = true

[aliases]
clone = ["git", "clone", "--colocate"]

[merge-tools.bat]
diff-args = ["--color=always", "$right"]
diff-invocation-mode = "file-by-file"

[merge-tools.cat]
diff-args = ["$right"]
diff-invocation-mode = "file-by-file"
